name: Release SDK nuget

on:
  push:
    tags: "*"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.101
    - name: Build
      run: dotnet build --configuration Release
    - name: Test
      run: dotnet test --no-build --configuration Release
    - name: Create the package
      run: dotnet pack --configuration Release src/Antares.Sdk /p:Version=${GITHUB_REF#refs/tags/}
    - name: Publish the package to GPR
      run: dotnet nuget push src/Antares.Sdk/bin/Release/*.nupkg -s "https://api.nuget.org/v3/index.json" -k ${{ secrets.NUGET_TOCKEN }}
